application: uberdjango
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: latest
- name: django
  version: "1.5"
- name: PIL
  version: "latest"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /static
  static_dir: static
# - url: /favicon\.ico
#   static_files: static/favicon.ico
- url: /.*
  script: wsgi.app

#import logging
#logging.info('1b- app.yaml')



