application: uberdjango
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: latest
- name: django
  version: "1.5"
- name: PIL
  version: latest
- name: matplotlib
  version: latest
- name: ssl
  version: "latest" 

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  UBERTOOL_BATCH_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com/'
  UBERTOOL_MONGO_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com'
  UBERTOOL_SECURE_SERVER: 'http://uberrest-topknotmeadows.rhcloud.com'
  UBERTOOL_REST_SERVER: 'http://localhost:7777'
  # UBERTOOL_REST_SERVER: 'http://54.83.18.251:7777'

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gz
- ^(.*/)?.*\.aux
- ^(.*/)?.*\.xcf
- ^(.*/)?.*\.php
- ^(.*/)?.*\.bak
- ^(.*/)?.*\.inc
- ^(.*/)?.*\.dark
- ^(.*/)?.*\.nofill
- ^(.*/)?.*\.SDR
- ^(.*/)?.*\MIT-LICENSE
- ^(.*/)?.*\LGPL-LICENSE
- ^(data/.*)
- ^(data/webice/.*)
- ^(data/webice/images/.*)
- ^(geneec/geneec_picloud/.*)
- ^(data/.*)
- ^(REST/.*)
- ^(przm/przm_picloud/.*)
- ^(pfam/pfam_picloud/.*)
- ^(generatepdf/generatepdf_picloud/.*)$
- ^(ubertool_pop/.*)    #Igonore the submodules that are there own GAE apps
- ^(ubertool_cts/.*)

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.app